// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Hts8EXUC3W1VlLfac7HJGXXDxHQ1xss',
    appId: '1:431113849971:web:44ee35f12d53493c4f6e06',
    messagingSenderId: '431113849971',
    projectId: 'japale-dace9',
    authDomain: 'japale-dace9.firebaseapp.com',
    storageBucket: 'japale-dace9.firebasestorage.app',
    measurementId: 'G-PZ7XE5EYQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAORFm-t0ek6KR41DiMuY5MvM_6BrFdH2g',
    appId: '1:431113849971:android:e1460d281b1d0eed4f6e06',
    messagingSenderId: '431113849971',
    projectId: 'japale-dace9',
    storageBucket: 'japale-dace9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAaYW0IOvthZYhou55eLSHVo62hsYCtZM',
    appId: '1:431113849971:ios:537659af54fdb01e4f6e06',
    messagingSenderId: '431113849971',
    projectId: 'japale-dace9',
    storageBucket: 'japale-dace9.firebasestorage.app',
    iosBundleId: 'com.example.japale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAaYW0IOvthZYhou55eLSHVo62hsYCtZM',
    appId: '1:431113849971:ios:537659af54fdb01e4f6e06',
    messagingSenderId: '431113849971',
    projectId: 'japale-dace9',
    storageBucket: 'japale-dace9.firebasestorage.app',
    iosBundleId: 'com.example.japale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Hts8EXUC3W1VlLfac7HJGXXDxHQ1xss',
    appId: '1:431113849971:web:f3544d0969ab2cec4f6e06',
    messagingSenderId: '431113849971',
    projectId: 'japale-dace9',
    authDomain: 'japale-dace9.firebaseapp.com',
    storageBucket: 'japale-dace9.firebasestorage.app',
    measurementId: 'G-5WW4T39J89',
  );
}
