// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Hts8EXUC3W1VlLfac7HJGXXDxHQ1xss',
    appId: '1:431113849971:web:44ee35f12d53493c4f6e06',
    messagingSenderId: '431113849971',
    projectId: 'japale-dace9',
    authDomain: 'japale-dace9.firebaseapp.com',
    storageBucket: 'japale-dace9.firebasestorage.app',
    measurementId: 'G-PZ7XE5EYQS',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCILjb4FVUFHm4m8wrMG1lUwHbjg0OM5U',
    appId: '1:497423748932:android:9a717ee77cf9aa42365111',
    messagingSenderId: '497423748932',
    projectId: 'japale-dace9-cc3dd',
    storageBucket: 'japale-dace9-cc3dd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEluwQ5DzVeCJOAbeEPBCYyFekiPq3woM',
    appId: '1:497423748932:ios:4c7cf069f9b54632365111',
    messagingSenderId: '497423748932',
    projectId: 'japale-dace9-cc3dd',
    storageBucket: 'japale-dace9-cc3dd.firebasestorage.app',
    iosBundleId: 'com.example.japale',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEluwQ5DzVeCJOAbeEPBCYyFekiPq3woM',
    appId: '1:497423748932:ios:4c7cf069f9b54632365111',
    messagingSenderId: '497423748932',
    projectId: 'japale-dace9-cc3dd',
    storageBucket: 'japale-dace9-cc3dd.firebasestorage.app',
    iosBundleId: 'com.example.japale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAawn-utW9ui3W4z2K2k4W5TjsLz9Z76Jo',
    appId: '1:497423748932:web:d9841dca59e6191d365111',
    messagingSenderId: '497423748932',
    projectId: 'japale-dace9-cc3dd',
    authDomain: 'japale-dace9-cc3dd.firebaseapp.com',
    storageBucket: 'japale-dace9-cc3dd.firebasestorage.app',
    measurementId: 'G-SCDB71VQTG',
  );
}
